version: "3.9"

volumes:
  pg_spring_users:
  kafka_data:
  zookeeper_data:

services:
  users_db:
    container_name: docker_spring_usersDB
    image: postgres:17.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=Nero
      - POSTGRES_PASSWORD=0907
      - POSTGRES_DB=users_db
    volumes:
      - pg_spring_users:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka
    ports:
      - "9092:9092"

  # user-service:
  #   container_name: user-service
  #   build:
  #     context: ./user-service
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - users_db
  #     - kafka
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://users_db:5432/users_db
  #     SPRING_DATASOURCE_USERNAME: Nero
  #     SPRING_DATASOURCE_PASSWORD: 0907
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   ports:
  #     - "8081:8081"

  # notification-service:
  #   container_name: notification-service
  #   build:
  #     context: ./notification-service
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - users_db
  #     - kafka
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://users_db:5432/users_db
  #     SPRING_DATASOURCE_USERNAME: Nero
  #     SPRING_DATASOURCE_PASSWORD: 0907
  #     KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   ports:
  #     - "8082:8082"