version: '3.1'

volumes:
  pg_spring_users:

services:
  users_db:
    container_name: docker_spring_usersDB
    image: postgres:17.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=Nero
      - POSTGRES_PASSWORD=0907
      - POSTGRES_DB=users_db
    volumes:
      - pg_spring_users:/var/lib/postgresql/data

    ports:
      - 5432:5432